services:
  db:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: apigraphql
      MYSQL_ROOT_USER: root
      MYSQL_PASSWORD: securepassword
      MYSQL_ROOT_PASSWORD: securepassword
